package ua.hpopov.parking.presentation.commands;

public enum CommandType {
	FORWARD_TO_LOGIN, FORWARD_TO_REGISTRATION, LOG_IN, RESTORE_PASSWORD, RESET_PASSWORD, REGISTER, 
	LOG_OUT, NEW_USERS, DECLINE_NEW_USER, CONFIRM_NEW_USER,
	NO_ACTION;
}
